FROM openjdk
WORKDIR usr/lib
ADD ./target/RecommendationService-0.0.1-SNAPSHOT.jar /usr/lib/RecommendationService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","RecommendationService-0.0.1-SNAPSHOT.jar"]