server:
  port: 8080
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    fetchRegistry: true
    registerWithEureka: true

#eureka:
#  client:
#    defaultZone: http://localhost:9091/eureka
#    fetchRegistry: true
#    registerWithEureka: true
